// Shared Tailwind utilities for the home page, including descendant and responsive variants.
export const homeStyles = {
  "home-site": [
    "home-site",
    "[background:#081a36]",
    "[color:#14243b]",
    "[--brand-accent:#2878bf]",
    "[&_a]:[-webkit-tap-highlight-color:transparent]",
    "[&_button]:[-webkit-tap-highlight-color:transparent]",
    "[&_a:focus-visible]:[outline:3px_solid_#86c9ff]",
    "[&_a:focus-visible]:[outline-offset:5px]",
    "[&_section[id]]:[scroll-margin-top:100px]",
    "[&_em]:[font-style:normal]",
    "[&_em]:[color:#92c6f1]",
    "[&_#about]:[background:#0c203a]",
    "[&_#about]:[color:#fff]",
    "[&_#about]:[padding:100px_max(7%,calc((100%_-_1260px)/2))]",
    "[&_#about>div]:[max-width:1260px]",
    "[&_#about_h2]:[font-family:Georgia,\"Times_New_Roman\",serif]",
    "[&_#about_h2]:[font-weight:400]",
    "[&_#about_[class*=\"glass\"]]:[border-radius:4px]",
    "[&_footer]:[color:#152c49]",
    "[&_footer]:[flex-wrap:wrap]",
    "[&_#contact]:[padding-top:70px]",
    "[&_#contact]:[padding-bottom:70px]",
    "[&_footer_small]:[color:#526078]",
    "[&_footer_img]:[width:95px]",
    "[&_footer_img]:[height:60px]",
    "[&_footer_img]:[object-fit:contain]",
    "max-[760px]:[&_#about]:[padding:65px_20px]",
    "max-[760px]:[&_#about_.grid]:[gap:20px]",
    "max-[760px]:[&_#about_h2]:[font-size:36px]",
    "max-[760px]:[&_footer]:[flex-direction:column]",
    "max-[760px]:[&_footer]:[gap:25px]",
  ].join(" "),
  "home-header": [
    "home-header",
    "[position:absolute]",
    "[inset:0_0_auto]",
    "[z-index:40]",
    "[max-width:1440px]",
    "[margin:auto]",
    "[display:flex]",
    "[align-items:center]",
    "[justify-content:space-between]",
    "[gap:24px]",
    "[padding:25px_5%]",
    "[border-bottom:1px_solid_#ffffff26]",
    "[color:white]",
    "[&_nav]:[display:flex]",
    "[&_nav]:[align-items:center]",
    "[&_nav]:[gap:30px]",
    "[&_nav]:[font-size:13px]",
    "[&_nav_a]:[padding:10px_0]",
    "[&_nav_a]:[transition:color_.2s]",
    "[&_nav_a:hover]:[color:#98ceff]",
    "[&_nav_a[aria-current]]:[border-bottom:1px_solid_#98ceff]",
    "[&_nav_.home-nav-contact]:[background:#2677bb]",
    "[&_nav_.home-nav-contact]:[border:1px_solid_#6bb0e355]",
    "[&_nav_.home-nav-contact]:[padding:12px_18px]",
    "[&_nav_.home-nav-contact]:[border-radius:3px]",
    "max-[900px]:[padding:20px_5%]",
    "max-[900px]:[gap:14px]",
    "max-[900px]:[&_nav]:[gap:18px]",
    "max-[900px]:[&_nav]:[font-size:11px]",
    "max-[760px]:[position:absolute]",
    "max-[760px]:[align-items:start]",
    "max-[760px]:[padding:16px_20px]",
    "max-[760px]:[flex-wrap:wrap]",
    "max-[760px]:[&_nav]:[width:100%]",
    "max-[760px]:[&_nav]:[justify-content:space-between]",
    "max-[760px]:[&_nav]:[gap:12px]",
    "max-[760px]:[&_nav_.home-nav-contact]:[background:transparent]",
    "max-[760px]:[&_nav_.home-nav-contact]:[border:0]",
    "max-[760px]:[&_nav_.home-nav-contact]:[padding:10px_0]",
  ].join(" "),
  "home-brand": [
    "home-brand",
    "[display:flex]",
    "[align-items:center]",
    "[gap:10px]",
    "[font-weight:750]",
    "[font-size:18px]",
    "[letter-spacing:.06em]",
    "[&_img]:[width:66px]",
    "[&_img]:[height:42px]",
    "[&_img]:[object-fit:contain]",
    "[&_small]:[display:block]",
    "[&_small]:[font-size:8px]",
    "[&_small]:[letter-spacing:.2em]",
    "[&_small]:[font-weight:400]",
    "[&_small]:[margin-top:4px]",
    "[&_small]:[color:#c2d2e6]",
    "max-[900px]:[font-size:14px]",
    "max-[760px]:[font-size:15px]",
    "max-[760px]:[&_img]:[width:52px]",
    "max-[760px]:[&_img]:[height:36px]",
  ].join(" "),
  "home-hero": [
    "home-hero",
    "[position:relative]",
    "[isolation:isolate]",
    "[min-height:700px]",
    "[display:flex]",
    "[align-items:center]",
    "[background:#081a36]",
    "[color:white]",
    "[padding:155px_7%_160px]",
    "[overflow:hidden]",
    "[&_h1]:[font-family:Georgia,\"Times_New_Roman\",serif]",
    "[&_h1]:[font-size:clamp(38px,4.7vw,70px)]",
    "[&_h1]:[font-weight:400]",
    "[&_h1]:[line-height:1.18]",
    "[&_h1]:[letter-spacing:-.035em]",
    "[&_h1]:[max-width:950px]",
    "min-[1600px]:[min-height:800px]",
    "max-[760px]:[padding:185px_24px_125px]",
    "max-[760px]:[min-height:690px]",
    "max-[760px]:[align-items:start]",
    "max-[760px]:[&_h1]:[font-size:40px]",
    "max-[760px]:[&_h1]:[line-height:1.23]",
  ].join(" "),
  "home-hero-image": [
    "home-hero-image",
    "[object-fit:cover]",
    "[object-position:center]",
  ].join(" "),
  "home-hero-shade": [
    "home-hero-shade",
    "[position:absolute]",
    "[inset:0]",
    "[background:linear-gradient(90deg,rgba(5,20,43,.93),rgba(9,35,65,.6)_52%,rgba(8,27,51,.15)),linear-gradient(0deg,#081a36,transparent_45%)]",
    "max-[760px]:[background:linear-gradient(90deg,#071a37e8,#112e5088),linear-gradient(0deg,#081a36,transparent)]",
  ].join(" "),
  "home-hero-content": [
    "home-hero-content",
    "[position:relative]",
    "[max-width:1260px]",
    "[width:100%]",
    "[margin:auto]",
  ].join(" "),
  "home-eyebrow": [
    "home-eyebrow",
    "[font-size:10px]",
    "[font-weight:700]",
    "[letter-spacing:.22em]",
    "[color:#8abde9]",
    "[margin-bottom:22px]",
  ].join(" "),
  "home-hero-description": [
    "home-hero-description",
    "[font-size:16px]",
    "[line-height:1.8]",
    "[color:#c7d5e5]",
    "[margin:26px_0_32px]",
    "max-[760px]:[font-size:14px]",
  ].join(" "),
  "home-actions": [
    "home-actions",
    "[display:flex]",
    "[align-items:center]",
    "[gap:28px]",
    "[flex-wrap:wrap]",
    "max-[760px]:[gap:22px]",
  ].join(" "),
  "home-button": [
    "home-button",
    "[display:inline-flex]",
    "[justify-content:center]",
    "[align-items:center]",
    "[gap:24px]",
    "[min-height:50px]",
    "[padding:14px_23px]",
    "[background:#2677bb]",
    "[border:1px_solid_#64a2d266]",
    "[border-radius:3px]",
    "[color:white]",
    "[font-size:13px]",
    "[font-weight:600]",
    "[transition:background_.2s,transform_.2s]",
    "[&:hover]:[background:#338ed5]",
    "[&:hover]:[transform:translateY(-2px)]",
    "max-[760px]:[font-size:12px]",
    "max-[760px]:[padding:14px_18px]",
    "max-[760px]:[gap:15px]",
  ].join(" "),
  "home-text-link": [
    "home-text-link",
    "[font-size:13px]",
    "[display:flex]",
    "[gap:24px]",
    "[align-items:center]",
    "[color:#d7e3f1]",
  ].join(" "),
  "home-hero-caption": [
    "home-hero-caption",
    "[position:absolute]",
    "[bottom:83px]",
    "[right:7%]",
    "[display:flex]",
    "[align-items:center]",
    "[gap:10px]",
    "[font-size:9px]",
    "[letter-spacing:.1em]",
    "[color:#b8c9dd]",
    "[flex-wrap:wrap]",
    "[&_strong]:[font-size:15px]",
    "[&_strong]:[color:white]",
    "[&_strong]:[letter-spacing:0]",
    "[&_strong]:[margin-left:10px]",
    "max-[760px]:[left:24px]",
    "max-[760px]:[right:24px]",
    "max-[760px]:[bottom:62px]",
    "max-[760px]:[font-size:8px]",
    "max-[760px]:[&_strong]:[margin-left:0]",
    "max-[760px]:[&>span:last-child]:[display:none]",
  ].join(" "),
  "home-live-dot": [
    "home-live-dot",
    "[width:6px]",
    "[height:6px]",
    "[background:#88d6b4]",
    "[border-radius:50%]",
    "[display:inline-block]",
  ].join(" "),
  "home-status": [
    "home-status",
    "[&_i]:[width:6px]",
    "[&_i]:[height:6px]",
    "[&_i]:[background:#88d6b4]",
    "[&_i]:[border-radius:50%]",
    "[&_i]:[display:inline-block]",
    "[position:absolute]",
    "[top:16px]",
    "[left:16px]",
    "[display:flex]",
    "[align-items:center]",
    "[gap:8px]",
    "[font-size:10px]",
    "[background:#091b35e0]",
    "[padding:9px_12px]",
    "[border:1px_solid_#a9c7e34d]",
    "[border-radius:2px]",
    "[color:#e3f4ee]",
    "[z-index:2]",
  ].join(" "),
  "home-pillars": [
    "home-pillars",
    "[position:relative]",
    "[z-index:2]",
    "[max-width:1260px]",
    "[margin:-44px_auto_0]",
    "[display:grid]",
    "[grid-template-columns:repeat(3,1fr)]",
    "[background:linear-gradient(120deg,#152e50,#0c203c)]",
    "[border:1px_solid_#57759366]",
    "[box-shadow:0_20px_45px_#081a3620]",
    "[color:white]",
    "[&_article]:[padding:30px_35px]",
    "[&_article]:[border-right:1px_solid_#ffffff1c]",
    "[&_article:last-child]:[border:0]",
    "[&_article>span]:[color:#82b4dd]",
    "[&_article>span]:[font-size:11px]",
    "[&_article>span]:[letter-spacing:.12em]",
    "[&_h2]:[font-size:20px]",
    "[&_h2]:[font-weight:600]",
    "[&_h2]:[margin:12px_0_8px]",
    "[&_p]:[font-size:13px]",
    "[&_p]:[line-height:1.8]",
    "[&_p]:[color:#b9c9db]",
    "max-[1350px]:[margin-left:7%]",
    "max-[1350px]:[margin-right:7%]",
    "max-[900px]:[&_article]:[padding:25px_22px]",
    "max-[900px]:[&_h2]:[font-size:17px]",
    "max-[760px]:[margin:-25px_20px_0]",
    "max-[760px]:[grid-template-columns:1fr]",
    "max-[760px]:[&_article]:[padding:22px_24px]",
    "max-[760px]:[&_article]:[border-right:0]",
    "max-[760px]:[&_article]:[border-bottom:1px_solid_#ffffff1c]",
    "max-[760px]:[&_article]:[display:grid]",
    "max-[760px]:[&_article]:[grid-template-columns:35px_1fr]",
    "max-[760px]:[&_article]:[column-gap:12px]",
    "max-[760px]:[&_article>span]:[grid-row:1/3]",
    "max-[760px]:[&_article>span]:[padding-top:5px]",
    "max-[760px]:[&_h2]:[margin:0_0_5px]",
    "max-[760px]:[&_p]:[font-size:12px]",
  ].join(" "),
  "home-projects": [
    "home-projects",
    "[padding:100px_max(7%,calc((100%_-_1260px)/2))]",
    "[background:radial-gradient(ellipse_at_top_right,#244a702c,transparent_55%),#081a36]",
    "[color:white]",
    "max-[760px]:[padding:65px_20px]",
  ].join(" "),
  "home-section-heading": [
    "home-section-heading",
    "[display:flex]",
    "[align-items:end]",
    "[justify-content:space-between]",
    "[gap:30px]",
    "[margin-bottom:38px]",
    "[&_h2]:[font-family:Georgia,\"Times_New_Roman\",serif]",
    "[&_h2]:[font-size:clamp(30px,3.3vw,48px)]",
    "[&_h2]:[line-height:1.2]",
    "[&_h2]:[letter-spacing:-.03em]",
    "[&>p]:[font-size:13px]",
    "[&>p]:[line-height:1.9]",
    "[&>p]:[color:#b7c9dc]",
    "max-[760px]:[align-items:start]",
    "max-[760px]:[flex-direction:column]",
    "max-[760px]:[gap:20px]",
    "max-[760px]:[&>p_br]:[display:none]",
  ].join(" "),
  "home-project-grid": [
    "home-project-grid",
    "[display:grid]",
    "[grid-template-columns:repeat(3,minmax(0,1fr))]",
    "[gap:22px]",
    "max-[900px]:[gap:14px]",
    "max-[760px]:[grid-template-columns:1fr]",
    "max-[760px]:[gap:24px]",
  ].join(" "),
  "home-project-card": [
    "home-project-card",
    "[min-width:0]",
    "[background:linear-gradient(135deg,#183353,#102640)]",
    "[border:1px_solid_#6c8ca443]",
    "[display:flex]",
    "[flex-direction:column]",
    "[transition:transform_.25s,border-color_.25s]",
    "[&:hover]:[transform:translateY(-5px)]",
    "[&:hover]:[border-color:#82b4dd88]",
  ].join(" "),
  "home-project-image": [
    "home-project-image",
    "[position:relative]",
    "[display:block]",
    "[aspect-ratio:4/3]",
    "[overflow:hidden]",
    "[background:#263d56]",
    "[&_img]:[object-fit:cover]",
    "[&_img]:[transition:transform_.5s]",
    "[&:hover_img]:[transform:scale(1.04)]",
    "max-[900px]:[aspect-ratio:1]",
    "max-[760px]:[aspect-ratio:3/2]",
  ].join(" "),
  "home-image-arrow": [
    "home-image-arrow",
    "[position:absolute]",
    "[bottom:16px]",
    "[right:16px]",
    "[display:grid]",
    "[place-items:center]",
    "[width:35px]",
    "[height:35px]",
    "[border:1px_solid_#ffffff80]",
    "[background:#0b264683]",
    "[border-radius:50%]",
    "[color:white]",
  ].join(" "),
  "home-project-body": [
    "home-project-body",
    "[padding:25px]",
    "[display:flex]",
    "[flex:1]",
    "[flex-direction:column]",
    "[&_h3]:[font-size:23px]",
    "[&_h3]:[line-height:1.3]",
    "[&_h3]:[letter-spacing:-.03em]",
    "[&_h3]:[margin:12px_0]",
    "[&>p:not(.home-project-category)]:[font-size:13px]",
    "[&>p:not(.home-project-category)]:[line-height:1.8]",
    "[&>p:not(.home-project-category)]:[color:#b9c9db]",
    "[&>p:not(.home-project-category)]:[margin-bottom:28px]",
    "max-[900px]:[padding:19px]",
    "max-[900px]:[&_h3]:[font-size:20px]",
    "max-[760px]:[padding:24px]",
    "max-[760px]:[&_h3]:[font-size:25px]",
  ].join(" "),
  "home-project-category": [
    "home-project-category",
    "[font-size:8px]",
    "[letter-spacing:.12em]",
    "[color:#8eb2d5]",
  ].join(" "),
  "home-card-link": [
    "home-card-link",
    "[display:flex]",
    "[justify-content:space-between]",
    "[align-items:center]",
    "[border-top:1px_solid_#ffffff21]",
    "[padding-top:17px]",
    "[margin-top:auto]",
    "[font-size:12px]",
    "[color:#a9d3f4]",
  ].join(" "),
  "home-blurred-image": [
    "home-blurred-image",
    "[filter:blur(9px)_saturate(.5)]",
    "[transform:scale(1.12)]!",
    "[opacity:.48]",
  ].join(" "),
  "home-coming-overlay": [
    "home-coming-overlay",
    "[position:absolute]",
    "[inset:0]",
    "[display:flex]",
    "[flex-direction:column]",
    "[justify-content:center]",
    "[align-items:center]",
    "[gap:12px]",
    "[background:#08213f44]",
    "[&_strong]:[font-size:16px]",
    "[&_strong]:[font-weight:500]",
    "[&_strong]:[letter-spacing:.22em]",
    "[&>span:last-child]:[font-size:11px]",
    "[&>span:last-child]:[color:#c1d2e4]",
  ].join(" "),
  "home-coming-symbol": [
    "home-coming-symbol",
    "[font-size:36px]",
    "[color:#9bbedd]",
  ].join(" "),
  "home-status-soon": [
    "home-status-soon",
    "[color:#c6d8e8]",
  ].join(" "),
  "home-soon-label": [
    "home-soon-label",
    "[color:#819bb5]",
  ].join(" "),
  "home-plan-banner": [
    "home-plan-banner",
    "[display:flex]",
    "[align-items:center]",
    "[justify-content:space-between]",
    "[gap:30px]",
    "[margin-top:45px]",
    "[padding:34px_38px]",
    "[background:linear-gradient(110deg,#193e66,#102842)]",
    "[border:1px_solid_#567b9e55]",
    "[&_.home-eyebrow]:[margin-bottom:10px]",
    "[&_h3]:[font-size:25px]",
    "[&_h3]:[margin-bottom:10px]",
    "[&_p:not(.home-eyebrow)]:[font-size:13px]",
    "[&_p:not(.home-eyebrow)]:[color:#b8cadf]",
    "max-[900px]:[padding:28px]",
    "max-[760px]:[padding:26px]",
    "max-[760px]:[flex-direction:column]",
    "max-[760px]:[align-items:start]",
    "max-[760px]:[&_h3]:[font-size:22px]",
    "max-[760px]:[&_.home-button]:[width:100%]",
  ].join(" "),
  "home-about-inner": [
    "home-about-inner",
    "[margin:auto]",
  ].join(" "),
  "home-about-heading": [
    "home-about-heading",
    "[display:grid]",
    "[grid-template-columns:1fr_1fr]",
    "[gap:70px]",
    "[align-items:start]",
    "[&_h2]:[font-size:clamp(36px,4vw,58px)]",
    "[&_h2]:[line-height:1.18]",
    "[&_h2]:[letter-spacing:-.035em]",
    "max-[900px]:[gap:35px]",
    "max-[760px]:[grid-template-columns:1fr]",
    "max-[760px]:[gap:25px]",
  ].join(" "),
  "home-about-description": [
    "home-about-description",
    "[font-size:15px]",
    "[line-height:1.9]",
    "[color:#b9c9db]",
    "[&_p+p]:[margin-top:18px]",
  ].join(" "),
  "home-history": [
    "home-history",
    "[display:grid]",
    "[grid-template-columns:repeat(4,1fr)]",
    "[margin:55px_0]",
    "[border-top:1px_solid_#789ab547]",
    "[border-bottom:1px_solid_#789ab547]",
    "[&_article]:[padding:30px_25px]",
    "[&_article]:[border-right:1px_solid_#789ab52b]",
    "[&_article:first-child]:[padding-left:0]",
    "[&_article:last-child]:[border-right:0]",
    "[&_article>span]:[font-size:30px]",
    "[&_article>span]:[color:#92c6f1]",
    "[&_article>span]:[font-weight:500]",
    "[&_h3]:[font-size:16px]",
    "[&_h3]:[margin:15px_0_8px]",
    "[&_p]:[font-size:12px]",
    "[&_p]:[line-height:1.8]",
    "[&_p]:[color:#a9bed4]",
    "max-[900px]:[&_article]:[padding:25px_18px]",
    "max-[760px]:[grid-template-columns:repeat(2,1fr)]",
    "max-[760px]:[margin:35px_0]",
    "max-[760px]:[&_article]:[padding:24px_16px]",
    "max-[760px]:[&_article:first-child]:[padding:24px_16px]",
    "max-[760px]:[&_article:nth-child(2)]:[border-right:0]",
    "max-[760px]:[&_article:nth-child(-n+2)]:[border-bottom:1px_solid_#789ab52b]",
  ].join(" "),
  "home-about-residence": [
    "home-about-residence",
    "[display:grid]",
    "[grid-template-columns:1fr_1fr]",
    "[background:#132d49]",
    "[border:1px_solid_#789ab53b]",
    "max-[760px]:[grid-template-columns:1fr]",
  ].join(" "),
  "home-about-photo": [
    "home-about-photo",
    "[position:relative]",
    "[min-height:390px]",
    "[overflow:hidden]",
    "[&_img]:[object-fit:cover]",
    "max-[760px]:[min-height:260px]",
  ].join(" "),
  "home-about-residence-body": [
    "home-about-residence-body",
    "[padding:40px]",
    "[&_h3]:[font-family:Georgia,\"Times_New_Roman\",serif]",
    "[&_h3]:[font-size:36px]",
    "[&_h3]:[margin-bottom:18px]",
    "[&>p:not(.home-eyebrow)]:[font-size:14px]",
    "[&>p:not(.home-eyebrow)]:[line-height:1.9]",
    "[&>p:not(.home-eyebrow)]:[color:#b9c9db]",
    "max-[900px]:[padding:28px]",
    "max-[760px]:[padding:25px]",
  ].join(" "),
  "home-about-stats": [
    "home-about-stats",
    "[display:grid]",
    "[grid-template-columns:repeat(3,1fr)]",
    "[gap:15px]",
    "[margin:32px_0]",
    "[&_strong]:[display:block]",
    "[&_strong]:[font-size:34px]",
    "[&_strong]:[font-weight:500]",
    "[&_strong]:[color:#92c6f1]",
    "[&_small]:[font-size:14px]",
    "[&_span]:[display:block]",
    "[&_span]:[font-size:11px]",
    "[&_span]:[color:#b9c9db]",
    "[&_span]:[margin-top:6px]",
    "max-[760px]:[gap:10px]",
    "max-[760px]:[&_strong]:[font-size:28px]",
  ].join(" "),
  "home-about-purpose": [
    "home-about-purpose",
    "[display:grid]",
    "[grid-template-columns:1fr_1fr]",
    "[gap:65px]",
    "[margin:75px_0]",
    "[&_article]:[border-left:2px_solid_#79b4e2]",
    "[&_article]:[padding-left:28px]",
    "[&_h3]:[font-family:Georgia,\"Times_New_Roman\",serif]",
    "[&_h3]:[font-size:32px]",
    "[&_h3]:[line-height:1.35]",
    "[&_h3]:[margin-bottom:20px]",
    "[&_article>p:last-child]:[font-size:14px]",
    "[&_article>p:last-child]:[line-height:1.9]",
    "[&_article>p:last-child]:[color:#b9c9db]",
    "[&_article>p:last-child]:[max-width:490px]",
    "max-[900px]:[gap:35px]",
    "max-[760px]:[grid-template-columns:1fr]",
    "max-[760px]:[margin:45px_0]",
    "max-[760px]:[gap:30px]",
    "max-[760px]:[&_h3]:[font-size:28px]",
  ].join(" "),
  "home-values-grid": [
    "home-values-grid",
    "[display:grid]",
    "[grid-template-columns:repeat(3,1fr)]",
    "[border-top:1px_solid_#789ab547]",
    "[border-left:1px_solid_#789ab547]",
    "[&_article]:[padding:28px]",
    "[&_article]:[border-right:1px_solid_#789ab547]",
    "[&_article]:[border-bottom:1px_solid_#789ab547]",
    "[&_article>span]:[font-size:11px]",
    "[&_article>span]:[letter-spacing:.15em]",
    "[&_article>span]:[color:#82b4dd]",
    "[&_h3]:[font-size:19px]",
    "[&_h3]:[margin:20px_0_12px]",
    "[&_p]:[font-size:13px]",
    "[&_p]:[line-height:1.85]",
    "[&_p]:[color:#b9c9db]",
    "max-[760px]:[grid-template-columns:repeat(2,minmax(0,1fr))]",
    "max-[760px]:[&_article]:[padding:22px_16px]",
    "max-[760px]:[&_h3]:[font-size:16px]",
    "max-[760px]:[&_p]:[font-size:12px]",
    "max-[380px]:[grid-template-columns:1fr]",
  ].join(" "),
  "home-about-statement": [
    "home-about-statement",
    "[text-align:center]",
    "[padding:65px_0_0]",
    "[margin-top:65px]",
    "[border-top:1px_solid_#789ab547]",
    "[&_p]:[font-family:Georgia,\"Times_New_Roman\",serif]",
    "[&_p]:[font-size:clamp(27px,3.2vw,44px)]",
    "[&_p]:[line-height:1.4]",
    "[&_p]:[letter-spacing:-.025em]",
    "[&>span]:[display:block]",
    "[&>span]:[font-size:10px]",
    "[&>span]:[letter-spacing:.22em]",
    "[&>span]:[color:#82b4dd]",
    "[&>span]:[margin-top:25px]",
    "max-[760px]:[margin-top:45px]",
    "max-[760px]:[padding-top:40px]",
  ].join(" "),
  "home-company-copy": [
    "home-company-copy",
    "[font-size:14px]",
    "[line-height:1.9]",
    "[color:#b9c9db]",
    "[&_p+p]:[margin-top:16px]",
    "[&_ul]:[list-style:disc]",
    "[&_ul]:[padding-left:20px]",
    "[&_ul]:[margin:16px_0]",
    "[&_li+li]:[margin-top:8px]",
    "max-[760px]:[font-size:13px]",
  ].join(" "),
  "home-company-motto": [
    "home-company-motto",
    "[padding:45px_0]",
    "[margin:45px_0]",
    "[&>span]:[margin:0_0_22px]",
  ].join(" "),
  "home-company-grid": [
    "home-company-grid",
    "[display:grid]",
    "[grid-template-columns:repeat(2,minmax(0,1fr))]",
    "[gap:24px]",
    "[margin-bottom:65px]",
    "[&_article]:[padding:30px]",
    "[&_article]:[border:1px_solid_#789ab53b]",
    "[&_article]:[background:#132d4955]",
    "[&_h3]:[font-size:13px]",
    "[&_h3]:[letter-spacing:.08em]",
    "[&_h3]:[color:#92c6f1]",
    "[&_h3]:[line-height:1.6]",
    "[&_h3]:[margin-bottom:20px]",
    "max-[760px]:[grid-template-columns:1fr]",
    "max-[760px]:[gap:16px]",
    "max-[760px]:[margin-bottom:45px]",
    "max-[760px]:[&_article]:[padding:24px]",
  ].join(" "),
  "home-company-experience": [
    "home-company-experience",
    "[margin-top:75px]",
    "[&_h2]:[font-size:clamp(30px,3.3vw,48px)]",
    "[&_h2]:[line-height:1.2]",
    "[&_.home-history]:[grid-template-columns:repeat(5,minmax(0,1fr))]",
    "[&_.home-history]:[margin-bottom:25px]",
    "max-[900px]:[&_.home-history]:[grid-template-columns:repeat(3,minmax(0,1fr))]",
    "max-[900px]:[&_.home-history_article]:[padding:24px_16px]",
    "max-[760px]:[margin-top:50px]",
    "max-[760px]:[&_.home-history]:[grid-template-columns:repeat(2,minmax(0,1fr))]",
    "max-[760px]:[&_.home-history_article]:[border-bottom:1px_solid_#789ab52b]",
    "max-[760px]:[&_.home-history_article:nth-child(even)]:[border-right:0]",
  ].join(" "),
  "home-company-path": [
    "home-company-path",
    "[color:#92c6f1]",
    "[font-size:13px]",
    "[margin-bottom:35px]",
    "[line-height:1.8]",
  ].join(" "),
  "home-company-details": [
    "home-company-details",
    "[margin-top:35px]",
    "[border-top:1px_solid_#789ab547]",
    "[&_details]:[border-bottom:1px_solid_#789ab547]",
    "[&_summary]:[display:flex]",
    "[&_summary]:[justify-content:space-between]",
    "[&_summary]:[align-items:center]",
    "[&_summary]:[gap:20px]",
    "[&_summary]:[padding:24px_0]",
    "[&_summary]:[cursor:pointer]",
    "[&_summary]:[font-size:16px]",
    "[&_summary]:[line-height:1.6]",
    "[&_summary]:[list-style:none]",
    "[&_summary::-webkit-details-marker]:[display:none]",
    "[&_summary_span]:[color:#92c6f1]",
    "[&_summary_span]:[font-size:24px]",
    "[&_summary_span]:[transition:transform_.2s]",
    "[&_details[open]_summary_span]:[transform:rotate(45deg)]",
    "[&_summary:focus-visible]:[outline:2px_solid_#92c6f1]",
    "[&_summary:focus-visible]:[outline-offset:4px]",
    "[&_.home-company-copy]:[padding:0_0_28px]",
    "[&_.home-company-copy]:[max-width:950px]",
    "max-[760px]:[&_summary]:[font-size:14px]",
  ].join(" "),
} as const;
